server:
  port: 7091

spring:
  application:
    name: seata-server

#logging:
##  config: classpath:logback-spring.xml
#  file:
#    path: ${user.home}/logs/seata
#  extend:
#    logstash-appender:
#      destination: 127.0.0.1:4560
#    kafka-appender:
#      bootstrap-servers: 127.0.0.1:9092
#      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata

nacos:
  server-addr: cloud-nacos:8848
  namespace:
  group: SEATA_GROUP
  username: nacos
  password: nacos

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      server-addr: ${nacos.server-addr}
      namespace: ${nacos.namespace}
      group: ${nacos.group}
      username: ${nacos.username}
      password: ${nacos.password}
      data-id: seataServer.properties

  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.server-addr}
      group: ${nacos.group}
      namespace: ${nacos.namespace}
      # tc集群名称
      cluster: default
      username: ${nacos.username}
      password: ${nacos.password}

  #  server:
  #    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login
