version: "3.5"

services:
  cloud-mysql:
    image: mysql:8.0
    container_name: cloud-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3305:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/mysql-files:/var/lib/mysql-files

  cloud-nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: cloud-nacos
    depends_on:
      - cloud-mysql
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=cloud-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=cloud_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - NACOS_AUTH_ENABLE=true
    volumes:
      - /D/docker-images/nacos/logs:/home/nacos/logs

#  cloud-seata:
#    image: seataio/seata-server:1.5.2
#    container_name: cloud-seata
#    ports:
#      - 7091:7091
#      - 8091:8091
#    environment:
#      - SEATA_PORT=8091
#      - STORE_MODE=file

  cloud-seata:
    image: seataio/seata-server:1.5.2
    container_name: cloud-seata
    depends_on:
      - cloud-mysql
      - cloud-nacos
    ports:
      - 7091:7091
      - 8091:8091
    environment:
      - STORE_MODE=db
      # 以SEATA_IP作为host注册seata server 宿主机ip
      - SEATA_IP=192.168.125.116
      - SEATA_PORT=8091
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"        #设置系统时区
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"  #设置时区
      # 假设我们通过docker cp命令把资源文件拷贝到相对路径`./seata-server/resources`中
      # 如有问题，请阅读上面的[注意事项]以及[使用自定义配置文件]
      - ./seata/resources/application.yml:/seata-server/resources/application.yml

#networks:
#  default:
#    external:
#      name: cloud
